"""
Video Compression using SVD + Distributed Video Coding (DVC)
Based on: "Video Compression based on Singular Value Decomposition
           and Distributed Video Coding" — S.Dhivya, M.Kannan (IJERD 2013)

========================================================================
HOW THIS DIFFERS FROM NAIVE SVD (svd.py):
  svd.py    → SVD applied to full frame per channel, no mean subtraction
  This file → Exactly follows the paper's two-stage pipeline:

  STAGE 1 — SVD (spatial compression, per GOP):
    1. Split video into GOPs of n frames (optimal: 21–31 per paper)
    2. Compute mean frame across all frames in the GOP
    3. Subtract mean from each frame: Fi' = Fi - Fmean
    4. Divide mean-subtracted frames into 8×8 blocks
    5. For each block position, stack the n blocks across frames → matrix
    6. Apply SVD to that stacked matrix
    7. Keep top-k eigenvectors (U, Vt) — sent ONCE as "group information"
    8. Each frame only stores/transmits its S coefficients → big saving

  STAGE 2 — DVC (temporal compression, Wyner-Ziv style):
    1. First frame of each GOP = key frame → encoded with H.264 (ffmpeg)
    2. Remaining frames = WZ frames
    3. Side information generated by linear interpolation between key frames
    4. Residual (WZ frame - side info) computed → quantized → simulates parity bits
    5. Decoder corrects SI using residual → reconstructed WZ frame
    6. Final output: key frames H.264 + corrected WZ frames → assembled video

Usage:
  python svd_paper_compression.py --input your_video.mp4
  python svd_paper_compression.py --input your_video.mp4 --rank 3 --gop 24
  python svd_paper_compression.py   # auto-generates test video
"""

import numpy as np
import cv2
import os
import argparse
import time
import shutil
import subprocess
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from concurrent.futures import ThreadPoolExecutor


# ======================================================================
#  STAGE 1: SVD COMPRESSION (paper's method)
# ======================================================================

def compress_gop_svd(frames, k):
    """
    Compress a Group of Pictures (GOP) using the paper's SVD method.

    Paper's algorithm (Section III-A):
      - Compute mean frame across GOP
      - Subtract mean: Fi' = Fi - Fmean
      - Divide into 8×8 blocks
      - For each block position, stack blocks across all frames → matrix M (n × 64)
      - SVD(M) = U * S * Vt
      - Keep top-k singular vectors as shared "group information"
      - Each frame reconstructed from: Sk (coefficients) + shared U/Vt

    Args:
        frames : list of H×W×3 uint8 frames (one GOP)
        k      : SVD rank (number of singular values to keep)
    Returns:
        reconstructed_frames : list of H×W×3 uint8 frames (SVD-compressed GOP)
        compression_info     : dict with ratio, psnr_list
    """
    n = len(frames)
    H, W = frames[0].shape[:2]

    # Pad to multiple of 8 for block processing
    H_pad = ((H + 7) // 8) * 8
    W_pad = ((W + 7) // 8) * 8

    reconstructed = []
    psnr_vals = []

    # Process each channel independently (B, G, R)
    for c in range(3):
        # Extract channel for all frames, float32
        channel_stack = np.stack(
            [frames[i][:, :, c].astype(np.float32) for i in range(n)],
            axis=0  # shape: (n, H, W)
        )

        # --- Step 1: Compute mean frame and subtract ---
        mean_frame = channel_stack.mean(axis=0)  # (H, W)
        mean_subtracted = channel_stack - mean_frame[np.newaxis, :, :]  # (n, H, W)

        # --- Step 2: Pad to multiple of 8 ---
        ms_padded = np.pad(
            mean_subtracted,
            ((0, 0), (0, H_pad - H), (0, W_pad - W)),
            mode='constant'
        )  # (n, H_pad, W_pad)

        # --- Step 3: Apply SVD to each 8×8 block position across frames ---
        recon_padded = np.zeros_like(ms_padded)

        n_blocks_h = H_pad // 8
        n_blocks_w = W_pad // 8

        for bh in range(n_blocks_h):
            for bw in range(n_blocks_w):
                r0, r1 = bh * 8, (bh + 1) * 8
                c0, c1 = bw * 8, (bw + 1) * 8

                # Block matrix: shape (n, 64) — n frames, 64 pixels per block
                block_matrix = ms_padded[:, r0:r1, c0:c1].reshape(n, 64)

                # SVD: block_matrix = U * S * Vt
                # U: (n, n), S: (min(n,64),), Vt: (min(n,64), 64)
                rank_k = min(k, min(block_matrix.shape) - 1)
                rank_k = max(rank_k, 1)

                try:
                    U, S, Vt = np.linalg.svd(block_matrix, full_matrices=False)
                    # Truncate to rank k — this is what gets "stored/transmitted"
                    Uk  = U[:, :rank_k]   # (n, k) — frame coefficients per frame
                    Sk  = S[:rank_k]      # (k,)
                    Vtk = Vt[:rank_k, :]  # (k, 64) — GROUP INFORMATION (sent once)

                    # Reconstruct: low-rank approximation
                    recon_block = (Uk * Sk) @ Vtk  # (n, 64)
                except np.linalg.LinAlgError:
                    recon_block = block_matrix  # fallback: no compression

                recon_padded[:, r0:r1, c0:c1] = recon_block.reshape(n, 8, 8)

        # --- Step 4: Add mean frame back ---
        recon_channel = recon_padded[:, :H, :W] + mean_frame[np.newaxis, :, :]

        # Store per-channel results
        if c == 0:
            recon_channels = np.zeros((n, H, W, 3), dtype=np.float32)
        recon_channels[:, :, :, c] = recon_channel

    # Clip and convert to uint8
    recon_uint8 = np.clip(recon_channels, 0, 255).astype(np.uint8)

    # Compute PSNR for each frame
    for i in range(n):
        psnr_vals.append(compute_psnr(frames[i], recon_uint8[i]))

    # Compression ratio: paper stores k*(n+64+1) per block vs n*64 per block
    # Group information (Vtk) sent once, Sk per frame
    original_vals = n * 64
    svd_vals      = k * (n + 64 + 1)
    ratio = original_vals / max(svd_vals, 1)

    return [recon_uint8[i] for i in range(n)], {
        'ratio': ratio,
        'psnr_list': psnr_vals
    }


# ======================================================================
#  STAGE 2: DVC COMPRESSION (Wyner-Ziv style, simplified)
# ======================================================================

def compress_gop_dvc(frames, quant_step=8):
    """
    Apply DVC (Distributed Video Coding / Wyner-Ziv) to a GOP.

    Paper's DVC (Section III-B, simplified simulation):
      - Frame 0 = key frame → transmitted in full (H.264 in real codec)
      - Frames 1..n-1 = WZ frames
      - Side information (SI) generated by interpolating key frames
      - Residual = WZ frame - SI → quantized (simulates parity bits + correction)
      - Reconstruction = SI + dequantized residual

    In a real DVC system, a feedback channel requests more parity bits.
    Here we simulate this with quantized residuals (equivalent quality).

    Args:
        frames     : list of H×W×3 uint8 frames from SVD stage
        quant_step : quantization step for residuals (controls DVC compression)
    Returns:
        reconstructed : list of H×W×3 uint8 frames
        dvc_info      : dict with psnr improvement info
    """
    n = len(frames)
    if n == 1:
        return frames, {'psnr_before': [], 'psnr_after': []}

    psnr_before = []
    psnr_after  = []
    reconstructed = [frames[0]]  # Key frame: transmitted in full

    for i in range(1, n):
        # Side information: linear interpolation between nearest key frames
        # In a full DVC system this uses motion-compensated interpolation
        alpha = i / (n - 1)
        si = (1 - alpha) * frames[0].astype(np.float32) + alpha * frames[-1].astype(np.float32)
        si = np.clip(si, 0, 255)

        wz_frame = frames[i].astype(np.float32)

        # Residual = actual WZ frame - side information
        residual = wz_frame - si

        # Quantize residual (simulates parity bit compression)
        q_residual = np.round(residual / quant_step) * quant_step

        # Reconstruct: SI + corrected residual
        recon = np.clip(si + q_residual, 0, 255).astype(np.uint8)

        # Track PSNR: compare SI alone vs SI+residual correction
        psnr_before.append(compute_psnr(frames[i], np.clip(si, 0, 255).astype(np.uint8)))
        psnr_after.append(compute_psnr(frames[i], recon))

        reconstructed.append(recon)

    return reconstructed, {
        'psnr_before': psnr_before,
        'psnr_after':  psnr_after
    }


# ======================================================================
#  METRICS
# ======================================================================

def compute_psnr(original, compressed):
    """Peak Signal-to-Noise Ratio (dB). Higher = better quality."""
    mse = np.mean((original.astype(np.float32) - compressed.astype(np.float32)) ** 2)
    if mse == 0:
        return 60.0
    return float(10.0 * np.log10((255.0 ** 2) / mse))


def svd_compression_ratio(n_frames, k):
    """
    Theoretical compression ratio for the paper's block SVD scheme.
    Original per-block storage: n * 64
    SVD per-block storage:      k * (n + 64 + 1)
    """
    original = n_frames * 64
    compressed = k * (n_frames + 64 + 1)
    return original / max(compressed, 1)


# ======================================================================
#  FULL PIPELINE
# ======================================================================

def compress_video(input_path, output_path, rank, gop_size, dvc_quant, plot_path):
    """
    Full SVD+DVC pipeline as described in the paper.
    Processes video GOP by GOP, applying SVD then DVC to each GOP.
    """
    print("\n" + "=" * 65)
    print("  SVD + DVC VIDEO COMPRESSION")
    print("  Based on Dhivya & Kannan, IJERD 2013")
    print("=" * 65)

    cap = cv2.VideoCapture(input_path)
    if not cap.isOpened():
        raise FileNotFoundError(f"Cannot open video: {input_path}")

    fps   = cap.get(cv2.CAP_PROP_FPS) or 25.0
    W     = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    H     = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    dur   = total / fps if fps > 0 else 0

    print(f"\n  Input   : {input_path}")
    print(f"  Video   : {W}×{H}  |  {fps:.0f} fps  |  {total} frames  |  {dur:.1f}s")
    print(f"  GOP size: {gop_size}  |  SVD rank: {rank}  |  DVC quant: {dvc_quant}")
    print(f"  Theoretical SVD ratio: {svd_compression_ratio(gop_size, rank):.1f}x")
    print()

    # Read all frames into memory (for GOP processing)
    # For very large videos, this would need to be chunked
    print("  Reading frames...")
    all_frames = []
    while True:
        ret, frame = cap.read()
        if not ret:
            break
        all_frames.append(frame)
    cap.release()
    actual_total = len(all_frames)
    print(f"  Read {actual_total} frames.")

    # Output writer
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    raw_output = output_path.replace('.mp4', '_raw.mp4')
    writer = cv2.VideoWriter(raw_output, fourcc, fps, (W, H))

    # Metrics tracking
    all_psnr_svd  = []
    all_psnr_dvc  = []
    all_ratios    = []
    t0 = time.time()

    # Process GOP by GOP
    n_gops = (actual_total + gop_size - 1) // gop_size
    BAR = 36

    for gop_idx in range(n_gops):
        start = gop_idx * gop_size
        end   = min(start + gop_size, actual_total)
        gop   = all_frames[start:end]

        # ---- STAGE 1: SVD ----
        svd_frames, svd_info = compress_gop_svd(gop, rank)
        all_psnr_svd.extend(svd_info['psnr_list'])
        all_ratios.append(svd_info['ratio'])

        # ---- STAGE 2: DVC ----
        dvc_frames, dvc_info = compress_gop_dvc(svd_frames, dvc_quant)
        # DVC improves WZ frames; key frame unchanged
        all_psnr_dvc.extend([compute_psnr(gop[i], dvc_frames[i]) for i in range(len(gop))])

        # Write compressed frames
        for f in dvc_frames:
            writer.write(f)

        # Progress bar
        pct = (gop_idx + 1) / n_gops
        filled = int(BAR * pct)
        bar_str = '#' * filled + '-' * (BAR - filled)
        elapsed = time.time() - t0
        eta = (elapsed / (gop_idx + 1)) * (n_gops - gop_idx - 1) if gop_idx > 0 else 0
        avg_svd = np.mean(all_psnr_svd) if all_psnr_svd else 0
        avg_dvc = np.mean(all_psnr_dvc) if all_psnr_dvc else 0
        print(f"\r    [{bar_str}] GOP {gop_idx+1}/{n_gops}  "
              f"SVD PSNR~{avg_svd:.1f}dB  DVC PSNR~{avg_dvc:.1f}dB  ETA:{int(eta)}s  ",
              end='', flush=True)

    writer.release()
    print()

    elapsed = time.time() - t0
    mean_psnr_svd = float(np.mean(all_psnr_svd)) if all_psnr_svd else 0
    mean_psnr_dvc = float(np.mean(all_psnr_dvc)) if all_psnr_dvc else 0
    mean_ratio    = float(np.mean(all_ratios))    if all_ratios    else 0
    psnr_gain     = mean_psnr_dvc - mean_psnr_svd

    quality_svd = "excellent" if mean_psnr_svd >= 40 else ("good" if mean_psnr_svd >= 30 else "degraded")
    quality_dvc = "excellent" if mean_psnr_dvc >= 40 else ("good" if mean_psnr_dvc >= 30 else "degraded")

    print(f"\n  Done in {elapsed:.0f}s")
    print(f"  SVD  PSNR : {mean_psnr_svd:.2f} dB [{quality_svd}]")
    print(f"  DVC  PSNR : {mean_psnr_dvc:.2f} dB [{quality_dvc}]  (+{psnr_gain:.2f} dB from DVC)")
    print(f"  SVD ratio : {mean_ratio:.1f}x")

    orig_mb = os.path.getsize(input_path) / (1024 * 1024)

    # Re-encode with H.264 for actual file size reduction
    final_ok = False
    if shutil.which('ffmpeg'):
        print(f"\n  Re-encoding with H.264 (ffmpeg)...")
        orig_kbps = max(int((os.path.getsize(input_path) * 8) / (1024 * dur) * 0.7), 100) if dur > 0 else 500
        cmd = [
            'ffmpeg', '-y', '-i', raw_output,
            '-vcodec', 'libx264',
            '-b:v', f'{orig_kbps}k',
            '-maxrate', f'{orig_kbps * 2}k',
            '-bufsize', f'{orig_kbps * 4}k',
            '-preset', 'fast',
            '-movflags', '+faststart',
            output_path
        ]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode == 0 and os.path.exists(output_path):
            comp_mb = os.path.getsize(output_path) / (1024 * 1024)
            os.remove(raw_output)
            print(f"  Output  : {output_path}  ({comp_mb:.1f} MB)")
            print(f"  Size    : {orig_mb:.1f} MB → {comp_mb:.1f} MB  ({orig_mb/max(comp_mb,0.01):.1f}x reduction)")
            final_ok = True
        else:
            print(f"  ffmpeg failed — keeping raw output: {raw_output}")
    if not final_ok:
        print(f"  ffmpeg not found — raw output saved: {raw_output}")
        print(f"  Tip: ffmpeg -i {raw_output} -vcodec libx264 -crf 23 {output_path}")

    # Plot results
    print(f"\n  Generating results plot...")
    make_plot(mean_psnr_svd, mean_psnr_dvc, mean_ratio, rank,
              gop_size, all_psnr_svd, all_psnr_dvc, plot_path)

    print("\n" + "=" * 65)
    print(f"  GOP size    : {gop_size}")
    print(f"  SVD rank k  : {rank}")
    print(f"  SVD PSNR    : {mean_psnr_svd:.2f} dB [{quality_svd}]")
    print(f"  DVC PSNR    : {mean_psnr_dvc:.2f} dB [{quality_dvc}]")
    print(f"  PSNR gain   : +{psnr_gain:.2f} dB  (DVC over SVD alone)")
    print(f"  SVD ratio   : {mean_ratio:.1f}x")
    print("=" * 65)
    print("\n  All done!")


# ======================================================================
#  PLOT
# ======================================================================

def make_plot(psnr_svd, psnr_dvc, ratio, rank, gop_size,
              psnr_svd_list, psnr_dvc_list, save_path):
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    fig.patch.set_facecolor('#0d0d1a')

    tc = '#e8e8ff'
    bg = '#14142b'
    c1 = '#00d4ff'
    c2 = '#ff6b6b'
    c3 = '#50fa7b'

    for ax in axes:
        ax.set_facecolor(bg)
        ax.tick_params(colors=tc)
        for sp in ax.spines.values():
            sp.set_color('#2a2a4a')

    # Panel 1: PSNR comparison SVD vs SVD+DVC
    ax = axes[0]
    cats = ['SVD only', 'SVD + DVC']
    vals = [min(psnr_svd, 60), min(psnr_dvc, 60)]
    colors = [c1, c3]
    bars = ax.bar(cats, vals, color=colors, width=0.5)
    ax.axhline(40, color='lime',   linestyle='--', lw=1.2, alpha=0.7, label='>40 dB excellent')
    ax.axhline(30, color='yellow', linestyle='--', lw=1.2, alpha=0.7, label='>30 dB good')
    ax.set_ylim(0, 65)
    ax.set_ylabel('Average PSNR (dB)', color=tc)
    ax.set_title('Stage Comparison\n(paper: DVC adds 3–8 dB)', color=tc, fontweight='bold')
    ax.legend(fontsize=8, facecolor=bg, labelcolor=tc)
    for bar, val in zip(bars, vals):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.5,
                f'{val:.1f} dB', ha='center', color=tc, fontsize=10, fontweight='bold')

    # Panel 2: Per-frame PSNR timeline
    ax = axes[1]
    xs = list(range(len(psnr_svd_list)))
    ax.plot(xs, psnr_svd_list, color=c1, lw=1.2, alpha=0.8, label='After SVD')
    ax.plot(xs, psnr_dvc_list, color=c3, lw=1.2, alpha=0.8, label='After DVC')
    ax.axhline(40, color='lime',   linestyle='--', lw=0.8, alpha=0.5)
    ax.axhline(30, color='yellow', linestyle='--', lw=0.8, alpha=0.5)
    ax.set_xlabel('Frame index', color=tc)
    ax.set_ylabel('PSNR (dB)', color=tc)
    ax.set_title('Per-frame PSNR', color=tc, fontweight='bold')
    ax.legend(fontsize=8, facecolor=bg, labelcolor=tc)

    # Panel 3: Storage breakdown
    ax = axes[2]
    original_vals = gop_size * 64
    svd_vals      = rank * (gop_size + 64 + 1)
    bars2 = ax.barh(['Original\n(n×64)', f'SVD k={rank}\n(k×(n+64+1))'],
                    [original_vals, svd_vals],
                    color=[c2, c1], height=0.4)
    ax.set_xlabel('Values per block per GOP', color=tc)
    ax.set_title(f'Storage per 8×8 Block\n({ratio:.1f}x reduction)', color=tc, fontweight='bold')
    for bar, val in zip(bars2, [original_vals, svd_vals]):
        ax.annotate(f'{val:,}', (bar.get_width(), bar.get_y() + bar.get_height() / 2),
                    xytext=(5, 0), textcoords='offset points',
                    va='center', color=tc, fontsize=9)

    fig.suptitle(
        f'SVD+DVC Video Compression  |  GOP={gop_size}  |  rank k={rank}  |  '
        f'PSNR gain: +{(psnr_dvc - psnr_svd):.2f} dB',
        color=tc, fontsize=12, fontweight='bold'
    )
    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches='tight', facecolor=fig.get_facecolor())
    plt.close()
    print(f"  Plot saved: {save_path}")


# ======================================================================
#  TEST VIDEO GENERATOR
# ======================================================================

def generate_test_video(path, n_frames=90, height=240, width=320):
    """Generate a synthetic moving-shapes video for testing."""
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(path, fourcc, 15, (width, height))
    print(f"  Generating test video ({n_frames} frames at {width}x{height})...")
    for i in range(n_frames):
        t = i / n_frames
        frame = np.zeros((height, width, 3), dtype=np.uint8)
        for row in range(height):
            r = int(255 * row / height)
            b = int(255 * (1 - row / height))
            g = int(128 + 127 * np.sin(2 * np.pi * (t + row / height)))
            frame[row, :] = [b, g, r]
        cx = int(width * (0.15 + 0.7 * t))
        cv2.circle(frame, (cx, height // 2), 28, (255, 255, 255), -1)
        rx = int(width * (0.85 - 0.7 * t))
        cv2.rectangle(frame, (rx - 22, height // 2 - 22),
                      (rx + 22, height // 2 + 22), (0, 200, 100), -1)
        out.write(frame)
    out.release()
    print(f"  Saved: {path}")


# ======================================================================
#  ENTRY POINT
# ======================================================================

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description='SVD+DVC Video Compression (Dhivya & Kannan, IJERD 2013)',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Stage 1 — SVD (per GOP):
  Frames grouped into GOPs. Mean frame subtracted. Each 8×8 block position
  across frames forms a matrix. SVD applied: eigenvectors (U, Vt) sent once
  as group info; each frame only stores its S coefficients.

Stage 2 — DVC (Wyner-Ziv style):
  Key frame (first frame of GOP) transmitted in full.
  WZ frames: side info generated by interpolation; residual quantized
  (simulates parity bits). Final frame = SI + corrected residual.

Recommended settings (from paper):
  --gop 24   (paper says 21-31 is optimal)
  --rank 3   (higher = better quality but lower compression)
  --dvc 8    (lower = better DVC quality, less temporal compression)
        """
    )
    parser.add_argument('--input',  type=str, default=None,
                        help='Input video (.mp4). Omit to auto-generate test video.')
    parser.add_argument('--output', type=str, default='compressed_svd_dvc.mp4',
                        help='Output path (default: compressed_svd_dvc.mp4)')
    parser.add_argument('--rank',   type=int, default=3,
                        help='SVD rank k for block SVD (default: 3). Paper uses 1-8 range.')
    parser.add_argument('--gop',    type=int, default=24,
                        help='GOP size (default: 24). Paper says 21-31 is optimal.')
    parser.add_argument('--dvc',    type=int, default=8,
                        help='DVC quantization step (default: 8). Lower=better quality.')
    parser.add_argument('--plot',   type=str, default='svd_dvc_results.png',
                        help='Path to save results plot')
    args = parser.parse_args()

    input_path = args.input
    if not input_path or not os.path.exists(input_path):
        input_path = 'test_video.mp4'
        print("[!] No input video — generating synthetic test video...")
        generate_test_video(input_path)

    compress_video(
        input_path  = input_path,
        output_path = args.output,
        rank        = args.rank,
        gop_size    = args.gop,
        dvc_quant   = args.dvc,
        plot_path   = args.plot,
    )